const not_loaded = formatDataAsArray(query_draft_details.data).length == 0;

let d = {
  ProductDraftID: not_loaded ? null : query_draft_details.data.ProductDraftID[0],
  AccountingCode: not_loaded ? null : query_draft_details.data.AccountingCode[0],
  AmazonOnly: not_loaded ? null : query_draft_details.data.AmazonOnly[0],
  AVPrice: not_loaded ? null : query_draft_details.data.AVPrice[0],
  BarcodeX3: not_loaded ? null : query_draft_details.data.BarcodeX3[0],
  Brand: not_loaded ? null : query_draft_details.data.Brand[0],
  X3YBrandCode: null, // reserved for SAGE
  Buyer: not_loaded ? null : query_draft_details.data.Buyer[0],
  Caliber: not_loaded ? null : query_draft_details.data.Caliber[0],
  CanadaAdmissible: not_loaded ? null : query_draft_details.data.CanadaAdmissible[0],
  CasePackUOM: not_loaded ? "EA" : query_draft_details.data.CasePackUOM[0],
  Category: not_loaded ? null : query_draft_details.data.Category[0],
  ExternalCategoryID: null, // reserved for SAGE
  Condition: not_loaded ? "NEW" : query_draft_details.data.Condition[0],
  CountryOfOrigin: not_loaded ? null : query_draft_details.data.CountryOfOrigin[0],
  Currency: not_loaded ? "USD" : query_draft_details.data.Currency[0],
  CustomsDutyRate: not_loaded ? null : query_draft_details.data.CustomsDutyRate[0],
  CreatedBy: not_loaded ? null : query_draft_details.data.CreatedBy[0],
  CreatedDateTime: not_loaded ? null : query_draft_details.data.CreatedDateTime[0],
  ChangedBy: not_loaded ? null : query_draft_details.data.ChangedBy[0],
  ChangedDateTime: not_loaded ? null : query_draft_details.data.ChangedDateTime[0],
  Description: not_loaded ? null : query_draft_details.data.Description[0],
  Description2: not_loaded ? null : query_draft_details.data.Description2[0],
  DimensionalUnit: not_loaded ? null : query_draft_details.data.DimensionalUnit[0],
  DistributionZone: not_loaded ? "P" : query_draft_details.data.DistributionZone[0],
  DLXBarcode: not_loaded ? null : query_draft_details.data.DLXBarcode[0],
  DLXLineNo: not_loaded ? null : query_draft_details.data.DLXLineNo[0],
  DLXPartUnit: not_loaded ? null : query_draft_details.data.DLXPartUnit[0],
  FBAProduct: not_loaded ? null : query_draft_details.data.FBAProduct[0],
  ECCN: not_loaded ? null : query_draft_details.data.ECCN[0],
  ETA: not_loaded ? null : query_draft_details.data.ETA[0],
  FreightPercent: not_loaded ? null : query_draft_details.data.FreightPercent[0],
  HazMatUN: not_loaded ? null : query_draft_details.data.HazMatUN[0],
  Height: not_loaded ? null : query_draft_details.data.Height[0],
  HTC: not_loaded ? null : query_draft_details.data.HTC[0],
  InsuranceLiabilityCode: not_loaded ? null : query_draft_details.data.InsuranceLiabilityCode[0],
  IsCouponAllowed: not_loaded ? null : query_draft_details.data.IsCouponAllowed[0],
  IsHazmat: not_loaded ? "1" : query_draft_details.data.IsHazmat[0],
  IssuePack: not_loaded ? null : query_draft_details.data.IssuePack[0],
  ITAR: not_loaded ? null : query_draft_details.data.ITAR[0],
  ItemModel: not_loaded ? null : query_draft_details.data.ItemModel[0],
  ItemType: not_loaded ? null : query_draft_details.data.ItemType[0],
  LandedCost: not_loaded ? null : query_draft_details.data.LandedCost[0],
  Length: not_loaded ? null : query_draft_details.data.Length[0],
  MPN: not_loaded ? null : query_draft_details.data.MPN[0],
  MSRP: not_loaded ? null : query_draft_details.data.MSRP[0],
  ParentID: not_loaded ? null : query_draft_details.data.ParentID[0],
  PackStockConv: not_loaded ? null : query_draft_details.data.PackStockConv[0],
  PriceList: not_loaded ? null : query_draft_details.data.PriceList[0],
  Priority: not_loaded ? null : query_draft_details.data.Priority[0],
  ProductCode: not_loaded ? null : query_draft_details.data.ProductCode[0],
  ProductID: not_loaded ? null : query_draft_details.data.ProductID[0],
  ProductStatus: not_loaded ? "1" : query_draft_details.data.ProductStatus[0],
  ProductSubType: not_loaded ? null : query_draft_details.data.ProductSubType[0],
  ProductType: not_loaded ? null : query_draft_details.data.ProductType[0],
  PYCode: not_loaded ? null : query_draft_details.data.PYCode[0],
  SalesChannels: not_loaded ? null : query_draft_details.data.SalesChannels[0],
  SellingPrice: not_loaded ? null : query_draft_details.data.SellingPrice[0],
  SpecialOrderWeeks: not_loaded ? null : query_draft_details.data.SpecialOrderWeeks[0],
  State: not_loaded ? "Draft" : query_draft_details.data.State[0],
  SupplierCasePackQuantity: not_loaded ? null : query_draft_details.data.SupplierCasePackQuantity[0],
  SupplierInsuranceLiabilityCode: not_loaded ? null : query_draft_details.data.SupplierInsuranceLiabilityCode[0],
  SupplierNumber: not_loaded ? null : query_draft_details.data.SupplierNumber[0],
  TaskURL: not_loaded ? null : query_draft_details.data.TaskURL[0],
  WAOnly: not_loaded ? true : query_draft_details.data.WAOnly[0],
  Weight: not_loaded ? null : query_draft_details.data.Weight[0],
  WeightUOM: not_loaded ? "LB" : query_draft_details.data.WeightUOM[0],
  Width: not_loaded ? null : query_draft_details.data.Width[0],
  Sites: [] 
};
draft.setValue(d);
//console.log(d);
//draft.setValue(query_draft_details.data); // JSON.stringify());
//localStorage.clear();
localStorage.setValue("draft", d);
//console.log(localStorage.values.draft);